# Generated by Django 4.2.30 on 2026-07-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_Name', models.CharField(max_length=20)),
                ('commodity_price', models.CharField(max_length=10)),
                ('commodity_image', models.ImageField(upload_to='commodity_image')),
            ],
        ),
        migrations.CreateModel(
            name='faceID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceID_name', models.CharField(default='', max_length=20)),
                ('faceID_number', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
                ('cSex', models.CharField(max_length=10)),
                ('cEmail', models.EmailField(max_length=100)),
                ('cPassward', models.CharField(max_length=20)),
                ('cPhoto1', models.ImageField(upload_to='faceID_image')),
                ('cPhoto2', models.ImageField(upload_to='faceID_image')),
                ('cPhoto3', models.ImageField(upload_to='faceID_image')),
            ],
        ),
    ]
