# Generated by Django 4.2.30 on 2026-07-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_seed_catalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceid',
            name='faceID_number',
        ),
        migrations.AddField(
            model_name='faceid',
            name='faceID_embeddings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
